/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import type { IntentFrame } from "@jarvis/memory-runtime";
import type {
  AcceptanceCriteria,
  TaskArtifactSpec,
  TaskEdge,
  TaskGraph,
  TaskGraphNodeKind,
  TaskInputRef,
  TaskNode,
  TaskOutputSpec,
} from "./taskGraph.js";
import { validateTaskGraph } from "./taskGraph.js";
import type {
  TaskGraphPlanDraft,
  TaskGraphPlanDraftStep,
} from "./taskGraphPlanner.js";

export type TaskGraphCompileResult =
  | { ok: true; graph: TaskGraph; rejectedReasons: [] }
  | { ok: false; graph: null; rejectedReasons: string[] };

function stableId(prefix: string, text: string): string {
  const normalized = text
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fff]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
  return `${prefix}-${normalized || "task"}`;
}

function nodeKindForDraftStep(step: TaskGraphPlanDraftStep): TaskGraphNodeKind {
  switch (step.kind) {
    case "memory_recall":
      return "recall";
    case "source_acquisition":
      return step.source?.type === "web" ? "research" : "read_many_files";
    case "local_workspace_discovery":
      return "list_directory";
    case "local_file_read":
      return step.source?.type === "local_directory"
        ? "read_many_files"
        : "read_file";
    case "evidence_extraction":
      return "extract_evidence";
    case "analysis":
      return "analyze";
    case "artifact_write":
      return "write_artifact";
    case "schedule":
      return "schedule";
    case "channel_push":
      return "push";
    case "delegate":
      return "delegate";
    case "final_response":
      return "respond";
  }
}

function capabilitiesForNodeKind(kind: TaskGraphNodeKind): string[] {
  switch (kind) {
    case "recall":
      return ["memory.recall"];
    case "research":
      return ["web.search"];
    case "analyze":
    case "extract_evidence":
      return ["llm.analyze"];
    case "write_file":
    case "write_artifact":
      return ["file.write"];
    case "read_file":
    case "list_directory":
    case "read_many_files":
      return ["file.read"];
    case "run_shell":
      return ["shell.run"];
    case "schedule":
      return ["task.schedule"];
    case "push":
      return ["channel.push"];
    case "delegate":
      return ["subagent.delegate"];
    case "respond":
      return ["llm.respond"];
  }
}

function outputForKind(
  kind: TaskGraphNodeKind,
  nodeId: string,
): TaskOutputSpec[] {
  const typeByKind: Partial<
    Record<TaskGraphNodeKind, TaskArtifactSpec["type"]>
  > = {
    recall: "memory",
    research: "source",
    read_file: "source",
    list_directory: "source",
    read_many_files: "source",
    analyze: "report",
    extract_evidence: "report",
    write_file: "file",
    write_artifact: "file",
    schedule: "scheduled_task",
    respond: "message",
    delegate: "message",
    push: "message",
  };
  const type = typeByKind[kind] ?? "message";
  return [
    {
      id: `${nodeId}-${type}`,
      type,
      description: `${kind} output generated by TaskGraphCompiler.`,
      required: true,
    },
  ];
}

function acceptance(
  id: string,
  type: AcceptanceCriteria["type"],
  description: string,
  params: Record<string, unknown> = {},
): AcceptanceCriteria {
  return {
    id,
    scope: "step",
    type,
    description,
    required: true,
    validator: `${type}_validator`,
    params,
  };
}

function acceptanceForKind(
  kind: TaskGraphNodeKind,
  nodeId: string,
): AcceptanceCriteria[] {
  switch (kind) {
    case "recall":
      return [
        acceptance(
          `${nodeId}-memory-retrieved`,
          "memory_retrieved",
          "Relevant memory or an explicit empty result is observed.",
          { nodeId },
        ),
      ];
    case "research":
      return [
        acceptance(
          `${nodeId}-source-count`,
          "source_count",
          "Source evidence is gathered for downstream analysis.",
          { nodeId, minSources: 1 },
        ),
      ];
    case "read_file":
    case "list_directory":
    case "read_many_files":
      return [
        acceptance(
          `${nodeId}-tool-result`,
          "tool_result",
          "Local source material is read successfully.",
          { nodeId, tool: "read_file" },
        ),
      ];
    case "write_file":
    case "write_artifact":
      return [
        acceptance(
          `${nodeId}-file-exists`,
          "file_exists",
          "The requested artifact exists.",
          { nodeId },
        ),
      ];
    case "schedule":
      return [
        acceptance(
          `${nodeId}-task-scheduled`,
          "task_scheduled",
          "The scheduled task is created or updated.",
          { nodeId },
        ),
      ];
    case "push":
      return [
        acceptance(
          `${nodeId}-tool-result`,
          "tool_result",
          "The channel push tool reports success.",
          { nodeId, tool: "push_to_channel" },
        ),
      ];
    default:
      return [
        acceptance(
          `${nodeId}-response-contains`,
          "response_contains",
          "The node output addresses its local purpose.",
          { nodeId },
        ),
      ];
  }
}

function titleForStep(step: TaskGraphPlanDraftStep): string {
  const path = step.source?.pathHint ? ` ${step.source.pathHint}` : "";
  const query = step.source?.queryHint ? ` ${step.source.queryHint}` : "";
  const destination = step.artifact?.destinationHint
    ? ` ${step.artifact.destinationHint}`
    : "";
  return `${step.purpose}${path}${query}${destination}`.trim();
}

function inputFrom(sourceNodeId: string): TaskInputRef {
  return {
    sourceNodeId,
    name: `${sourceNodeId}.output`,
    required: true,
  };
}

function buildEdges(nodes: TaskNode[]): TaskEdge[] {
  return nodes.flatMap((node) =>
    node.inputs
      .filter((input) => input.sourceNodeId)
      .map((input) => ({
        from: input.sourceNodeId!,
        to: node.id,
        reason: "planner draft dependency",
      })),
  );
}

function findPriorContentNodeId(nodes: TaskNode[]): string | null {
  return (
    [...nodes]
      .reverse()
      .find(
        (node) =>
          ["analyze", "respond", "research", "read_file", "recall"].includes(
            node.kind,
          ) ||
          ["extract_evidence", "read_many_files", "list_directory"].includes(
            node.kind,
          ),
      )?.id ?? null
  );
}

export function compileTaskGraphDraft(
  intent: IntentFrame,
  draft: TaskGraphPlanDraft,
): TaskGraphCompileResult {
  const rejectedReasons: string[] = [];
  const stepIdToNodeId = new Map<string, string>();
  const nodes: TaskNode[] = [];

  for (const step of draft.steps) {
    const nodeId = step.id || stableId("compiled-node", step.purpose);
    if (stepIdToNodeId.has(step.id)) {
      rejectedReasons.push(`duplicate_step_id:${step.id}`);
      continue;
    }
    stepIdToNodeId.set(step.id, nodeId);
  }

  for (const step of draft.steps) {
    const kind = nodeKindForDraftStep(step);
    const nodeId = stepIdToNodeId.get(step.id) ?? step.id;
    const inputs = step.dependsOn
      .map((dep) => stepIdToNodeId.get(dep))
      .filter((dep): dep is string => Boolean(dep))
      .map(inputFrom);
    const node: TaskNode = {
      id: nodeId,
      title: titleForStep(step),
      kind,
      requiredCapabilities: capabilitiesForNodeKind(kind),
      inputs,
      outputs: outputForKind(kind, nodeId),
      acceptanceCriteria: acceptanceForKind(kind, nodeId),
      retryPolicy: {
        maxAttempts: kind === "respond" ? 1 : 2,
        strategy: "same",
      },
      optional: !step.required,
    };
    if (
      (kind === "write_file" || kind === "write_artifact") &&
      node.inputs.length === 0
    ) {
      const producerId = findPriorContentNodeId(nodes);
      if (producerId) {
        node.inputs = [inputFrom(producerId)];
      } else {
        rejectedReasons.push(`write_without_content_producer:${step.id}`);
      }
    }
    nodes.push(node);
  }

  for (const step of draft.steps) {
    for (const dep of step.dependsOn) {
      if (!stepIdToNodeId.has(dep)) {
        rejectedReasons.push(`unknown_dependency:${step.id}:${dep}`);
      }
    }
  }

  if (rejectedReasons.length > 0) {
    return { ok: false, graph: null, rejectedReasons };
  }

  const graph: TaskGraph = {
    id: stableId("graph", draft.goal || intent.richIntent.userGoal),
    rootTaskId: stableId("task", draft.goal || intent.richIntent.userGoal),
    nodes,
    edges: buildEdges(nodes),
    globalConstraints: [
      {
        id: "memory-boundary",
        description: `Respect query subject boundary: ${intent.subject}.`,
        source: "memory_contract",
      },
    ],
    acceptanceCriteria: [
      acceptance(
        "task-compiled-goal",
        "response_contains",
        "The compiled graph supports the requested user goal.",
        { goal: draft.goal },
      ),
    ],
    status: "planned",
    blockedReasons: [],
  };

  const validationFailures = validateTaskGraph(graph).filter(
    (gate) => !gate.ok && gate.blocking,
  );
  if (validationFailures.length > 0) {
    return {
      ok: false,
      graph: null,
      rejectedReasons: validationFailures.map(
        (gate) => `${gate.code}:${gate.message}`,
      ),
    };
  }

  return { ok: true, graph, rejectedReasons: [] };
}
